### PR TITLE
Fix for issue #5

### LINKED ISSUE #5: JavaFX Thread stops working
There is an issue with javafx where if a scene is not open for a short period of time (measured in milliseconds) the jfx thread terminates. This is by design in jfx, but for our use if there is a frame or two without a jfx ui open, then it is no longer possible to open another one as the jfx thread has stopped.

The fix is to place `Platform.setImplicitExit(false);` in the `initFx()` function in the `JmeFxContainerImpl` class.

```
private void initFx() {
        PlatformImpl.startup(() -> {
            switch (Pixels.getNativeFormat()) {
                case Pixels.Format.BYTE_ARGB:
                    try {
                        nativeFormat.complete(Format.ARGB8);
                        reorderData = null;
                    } catch (final Exception exc1) {
                        nativeFormat.complete(Format.ABGR8);
                        reorderData = JmeFxContainerImpl::reorder_ARGB82ABGR8;
                    }
                    break;
                case Pixels.Format.BYTE_BGRA_PRE:
                    try {
                        nativeFormat.complete(Format.BGRA8);
                        reorderData = null;
                    } catch (final Exception exc2) {
                        nativeFormat.complete(Format.ABGR8);
                        reorderData = JmeFxContainerImpl::reorder_BGRA82ABGR8;
                    }
                    break;
                default:
                    throw new IllegalArgumentException("Not supported javaFX pixel format " + Pixels.getNativeFormat());
            }
        });
        Platform.setImplicitExit(false);  //<----- PUT IT HERE
    }
```

### PR DESCRIPTION
**Pull request by tlf30**
Fix for issue #5 

Closes #5

### CODE REVIEW

**Comment by tlf30** [comment]
@jayfella can you please look at this, currently have an application that is broken due to this bug, this PR fixes it.

**Comment by jayfella** [comment]
Ill take a look today.

**Comment by jayfella** [comment]
I'm going to accept this as it won't affect anything other than the issue you mentioned, but I'm a little curious as to how you are in a position where there is never any scene present.

The implementation places an anchorpane in the scene at all times, and any jfx controls are added to that, so a scene should always be present.

**Comment by tlf30** [comment]
I am probably doing something dumb inside of my GUIManager when handling my jfx UIs. I will throw you a message on the jme forums with my implementation. 

Is this merge available in jcenter?

**Pull request merged**
