### PR TITLE
Implemented changes for

### PR DESCRIPTION
**Pull request by Klaus1987**
JME-JFX Mouse and Key Button Crossinput

### CODE REVIEW

**Comment by jayfella** [comment]
Firstly thank you for taking the time to submit a PR. Much appreciated.

The functional interface avoids the need to use proxy classes. I'm fine with that. I'm not sure why you seperated the input maps into a class of their own, though. If you had implemented an `InputStorage` interface so the input could be read from other sources other than "memory" such as a database or filesystem I could see the merit, but in this case there would never be a need to do so. I feel like putting the maps into the MemoryInputHandler would have sufficed.

Other than that everything seems fine to me.

**Comment by Klaus1987** [comment]
JmeMemoryInput.class is more or less a dto to pass the maps to 
JmeMemoryInputHandler and JmeFxEventConsumeAllowedFunction
Yes, I can remove the class and directly store the maps.
Also, we can remove CrossInputHandler and the ProxyEvent.
KEY_CODE_TO_JME can be modified back to private.
I will commit this to my branch tomorrow.

Glad you are fine with the solution approach.

**Comment by jayfella** [comment]
As far as I can see you've removed all thread safety procedures I put in place. The hashmaps are read by both the JME and JFX thread. They are added and removed by the JME thread, and removed by the JFX thread.

**Comment by Klaus1987** [comment]
The hashmaps are now only updated from the JME Thready. (The data is only updated from the raw input listeners) There is no JFX Thread here involved anymore. (removal of the map is not triggered anymore from the JFX Listener)
So there is no point in using thread safe maps, since it is only updated from JME thread.

**Comment by jayfella** [comment]
Sorry it's taken so long, I moved house and so didn't have internet for 10 days.

This is great. PR has been merged.

**Comment by jayfella** [comment]
Version 1.1.5 is now available on jcenter with these implemented changes. Thanks again for your contribution.

**Comment by Klaus1987** [comment]
You're welcome. Thank you for providing 1.1.5. Already in use on my project.

**Pull request merged**
